Agenstvo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),                # main.app
    path('zayavka/', include('zayavki.urls', namespace='zayavki')),  # zayavki.app
    path('search/', include('search.urls', namespace='search')),     # search.app
    path('api/', include('api.urls', namespace='api')),              # api
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import RealtyViewSet, ZayavkaCreateView, SearchApi, CategoriesApi

router = routers.DefaultRouter()
router.register('realty', RealtyViewSet)
router.register('zayavka', ZayavkaCreateView)
router.register('search', SearchApi)
router.register('categories', CategoriesApi)

app_name = 'api'
# /api/
urlpatterns = [
    path('', include(router.urls)),
]

main/urls.py
from django.urls import path

from .views import ObjectsMain, detailobjectview, ManagerDetailView

app_name = 'main'

# ''/
urlpatterns = [
    path('', ObjectsMain.as_view(), name='home'),
    path('detail/<int:pk>/', detailobjectview, name='object_info'),
    path('manager/<int:pk>/', ManagerDetailView.as_view(), name='manager_info'),


]

search/urls.py
from django.urls import path

from search.views import SearchResult

app_name = 'search'

urlpatterns = [
    path('', SearchResult.as_view(), name='search'),
]

zayavki/urls.py
from django.urls import path

from zayavki.views import ZayavkaViews

app_name = 'zayavki'

# /zayavka/
urlpatterns = [
    path('', ZayavkaViews.as_view(), name='zayavka'),
]

main/models.py
from django.db import models
import datetime

from django.urls import reverse


class Realty(models.Model):
    title = models.CharField(max_length=100)
    info = models.TextField()
    price = models.IntegerField()
    cat = models.ForeignKey('Category', on_delete=models.PROTECT)
    person = models.ForeignKey('Manager', null=True, blank=True, on_delete=models.PROTECT)
    img = models.ImageField(upload_to='house_image', blank=True)
    email = models.EmailField('Users', blank=True)

    def get_absolute_url(self):
        return reverse('main:object_info', args=[self.id])


class Gallery(models.Model):
    image = models.ImageField(upload_to='house_image')
    realty = models.ForeignKey(Realty, on_delete=models.CASCADE, related_name='images')


class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.name}'


class Manager(models.Model):
    name = models.CharField(max_length=30)
    surname = models.TextField(null=True, blank=True)
    phone = models.IntegerField(null=True, blank=True)
    email = models.TextField(null=True, blank=True)
    img = models.ImageField(blank=True)

    def __str__(self):
        return self.name

main/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView

from main.models import Realty, Category, Manager
from zayavki.forms import ZayavkaForm


# list objects on index page
class ObjectsMain(ListView):
    model = Realty
    template_name = 'main.html'
    context_object_name = 'realty'

    def get_queryset(self):
        queryset = super().get_queryset()
        rnd_obj = Realty.objects.order_by('?')[:3]
        return rnd_obj


def detailobjectview(request, pk):
    info = Realty.objects.get(pk=pk)

    if request.method == 'POST':
        form = ZayavkaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:home')
    else:
        form = ZayavkaForm()
    return render(request, 'detail.html', {'info': info, 'form': form})




class ManagerDetailView(DetailView):
    template_name = 'manager_info.html'
    model = Manager
    context_object_name = 'manager_info'

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Агентство недвижимости</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Plato
  * Updated: May 30 2023 with Bootstrap v5.3.0
  * Template URL: https://bootstrapmade.com/plato-responsive-bootstrap-website-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->

<style>
.realty {
    font-size: 14px;
    color: #d97c11;
}
</style>


</head>

<body>
  <div class="wrap">

    <!-- ======= Hero Section ======= -->
    {% if request.path == '/' %}
    <section id="hero">
      <div class="hero-container" data-aos="fade-up">
        <h1>Plaza Realty</h1>
        <h2>Агентство вашей недвижимости!</h2>
      </div>
    </section><!-- End Hero -->
    {% else %}
    {% endif %}


    <!-- ======= Header ======= -->
    <header id="header" class="d-flex align-items-center">
      <div class="container d-flex align-items-center justify-content-between">

        <div class="logo">
          <h1 class="text-light"><a href="{% url 'main:home' %}">
              <span>PLAZA <span class="realty">realty</span></span>
          </a></h1>
          <!-- Uncomment below if you prefer to use an image logo -->
          <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
        </div>

        <nav id="navbar" class="navbar">
          <ul>

            <li><a class="nav-link scrollto {% if request.path == '/' %} active {% else %} {% endif %}" href="{% url 'main:home' %}">Главная</a></li>
            <li><a class="nav-link scrollto {% if request.path == '/search/' %} active {% else %} {% endif %}" href="{% url 'search:search' %}">Поиск</a></li>
            <li><a class="nav-link scrollto {% if request.path == '/search/' %} active {% else %} {% endif %}" href="{% url 'search:search' %}">О нас</a></li>


{#            <li><a class="nav-link scrollto" href="#services">Services</a></li>#}
{#            <li><a class="nav-link scrollto " href="#portfolio">Portfolio</a></li>#}
{#            <li><a class="nav-link scrollto" href="#pricing">Pricing</a></li>#}
{#            <li><a class="nav-link scrollto" href="#team">Team</a></li>#}
{#            <li><a href="blog.html">Blog</a></li>#}
{#            <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>#}
{#              <ul>#}
{#                <li><a href="#">Drop Down 1</a></li>#}
{#                <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>#}
{#                  <ul>#}
{#                    <li><a href="#">Deep Drop Down 1</a></li>#}
{#                    <li><a href="#">Deep Drop Down 2</a></li>#}
{#                    <li><a href="#">Deep Drop Down 3</a></li>#}
{#                    <li><a href="#">Deep Drop Down 4</a></li>#}
{#                    <li><a href="#">Deep Drop Down 5</a></li>#}
{#                  </ul>#}
{#                </li>#}
{#                <li><a href="#">Drop Down 2</a></li>#}
{#                <li><a href="#">Drop Down 3</a></li>#}
{#                <li><a href="#">Drop Down 4</a></li>#}
{#              </ul>#}
{#            </li>#}
            <li><a class="nav-link scrollto {% if request.path == '/zayavka/' %} active {% else %} {% endif %} " href="{% url 'zayavki:zayavka' %}">Подать заявку</a></li>
            <li><a class="nav-link scrollto {% if request.path == '/zayavka/' %} active {% else %} {% endif %} " href="{% url 'zayavki:zayavka' %}">Контакты</a></li>
{#            <li><a class="nav-link scrollto" href="{% url 'zayavka' %}">О компании</a></li>#}
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

      </div>
    </header><!-- End Header -->

    <main id="main">



        {% block content %}

        {% endblock %}


    <!-- ======= Footer ======= -->
    <footer id="footer">

{#      <div class="footer-newsletter">#}
{#        <div class="container">#}
{#          <div class="row justify-content-center">#}
{#            <div class="col-lg-6">#}
{#              <h4>Join Our Newsletter</h4>#}
{#              <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>#}
{##}
{##}
{#              <form action="" method="post">#}
{#                <input type="email" name="email"><input type="submit" value="Subscribe">#}
{#              </form>#}
{##}
{##}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}

      <div class="footer-top">
        <div class="container">
          <div class="row">

            <div class="col-lg-3 col-md-6 footer-contact">
              <h3>Plato</h3>
              <p>
                A108 Adam Street <br>
                New York, NY 535022<br>
                United States <br><br>
                <strong>Phone:</strong> +1 5589 55488 55<br>
                <strong>Email:</strong> info@example.com<br>
              </p>
            </div>

            <div class="col-lg-3 col-md-6 footer-links">
              <h4>Useful Links</h4>
              <ul>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
              </ul>
            </div>

            <div class="col-lg-3 col-md-6 footer-links">
              <h4>Our Services</h4>
              <ul>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
              </ul>
            </div>

            <div class="col-lg-3 col-md-6 footer-links">
              <h4>Our Social Networks</h4>
              <p>Cras fermentum odio eu feugiat lide par naso tierra videa magna derita valies</p>
              <div class="social-links mt-3">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
              </div>
            </div>

          </div>
        </div>
      </div>

      <div class="container py-4">
        <div class="copyright">
          &copy; Copyright <strong><span>Plato</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/plato-responsive-bootstrap-website-template/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
    </footer><!-- End Footer -->

  </div>

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="a{% static 'vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/detail.html
    {% extends 'base.html' %}
{% load static %}
    {% block content %}
<!-- Page content -->










<!-- ======= Portfolio Details Section ======= -->
      <section id="portfolio-details" class="portfolio-details">
        <div class="container">

          <div class="row gy-4">

            <div class="col-lg-8">
              <div class="portfolio-details-slider swiper">
                <div class="swiper-wrapper align-items-center">

                {% load thumbnail %}

                  <div class="swiper-slide">
                      <a href="{{ info.img.url }}" target="_blank">
                        <img src="{% thumbnail info.img 940x0 %}" alt="">
                      </a>
                  </div>


                    {% for i in info.images.all %}
                  <div class="swiper-slide">
                      <a href="{{ i.image.url }}" target="_blank">
                        <img src="{% thumbnail i.image 940x0 %}" alt="">
                      </a>
                  </div>
                    {% endfor %}



                </div>
                <div class="swiper-pagination"></div>
              </div>
            </div>

            <div class="col-lg-4">
              <div class="portfolio-info">
                <h3>{{ info.title }}</h3>
                <ul>
                  <li><strong>Тип </strong>: {{ info.cat }}</li>
                  <li><strong>Цена </strong>: {{ info.price }}</li>
                  <li><strong>Менеджер </strong>: {{ info.person }} ID: {{ info.person.id }}</li>
                  <li><strong>Подать </strong> <a href="{% url 'zayavki:zayavka' %}">заявку</a></li>


               <a href="{{ request.build_absolute_uri }}">{{ request.build_absolute_uri }}</a>


                </ul>
              </div>
              <div class="portfolio-description">
{#                <h2>This is an example of portfolio detail</h2>#}
                <p>
                  {{ info.info }}
                </p>
              </div>
            </div>

          </div>

        </div>
      </section><!-- End Portfolio Details Section -->

    </main><!-- End #main -->


    <!-- Form Zayavka -->
      <div class="container">
          <form action="" method="post">
                {% csrf_token %}
             <div class="row">

                 <!-- name field -->
                  <div class="col-md-6 form-group">
                      <input type="text" name="name" class="form-control"  placeholder="Your Name" required>
                  </div>

                 <!-- email field -->
                  <div class="col-md-6 form-group mt-3 mt-md-0">
                      <input type="email" class="form-control" name="email"  placeholder="Your Email" required>
                  </div>
             </div>

              <!-- question field -->
             <div class="form-group mt-3">
                <input type="question" class="form-control" name="question"  placeholder="Your question" required>
             </div>

              <!-- Hidden field for manager ID-->
             <input type="hidden" class="form-control" name="manager_id"  placeholder="manager_id" required value="{{ info.person.id }}">
              <br>

              <!-- Button -->
              <div class="text-center"><button type="submit" class="btn btn-success" >Send Message</button></div>

          </form>
      </div>
        <!-- END Form Zayavka --
<br>
<br>
<br>
{% endblock %}

templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}



  <!-- ======= Features Section ======= -->
  <section id="features" class="features">
    <div class="container">
      <div class="row d-flex justify-content-center">
        {% for object in realty %}
        <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
          <div class="card">
            <a href="{{ object.get_absolute_url }}"><img src="{{ object.img.url }}" class="card-img-top" alt="..."></a>
            <div class="card-body">
              <i class="bx bx-tachometer"></i>
              <h5 class="card-title"><a href="{{ object.get_absolute_url }}">{{object.title}}</a></h5>
              <p class="card-text">{{ object.info }}</p>
            </div>
          </div>
        </div>
        {% endfor %}
        <div class="col-lg-12 d-flex justify-content-center">
          <a href="{% url 'search:search' %}" class="btn btn-custom mx-auto mt-5">Все объекты</a>
        </div>
      </div>
    </div>
  </section>

  <style>
    .btn-custom {
      background-color: #fff;
      color: #000;
      border: 2px solid #000;
    }
    .btn-custom:hover,
    .btn-custom:focus {
      background-color: #fff;
      color: #000;
      border: 2px solid #000;
    }
  </style>

{% endblock %}

templates/manager_info.html
    {% extends 'base_old.html' %}
    {% block content %}
<!-- Page content -->
<div class="w3-content w3-padding" style="max-width:1564px">

  <!-- Project Section -->
  <div class="w3-container w3-padding-32" id="projects">
{#    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">{{ detail.title }}</h3>#}

      <h1> Менеджер: </h1>
          <p>
        Имя: {{ manager_info.name }}
          </p>

         <p>
         Фамилия: {{ manager_info.surname }}
          </p>

        <p>
            Телефон: {{ manager_info.phone }}
          </p>

        <p>
        Email: {{ manager_info.email }}
          </p>


  </div>
  <div class="w3-container w3-padding-32" id="about">

  </div>



 {% endblock %}

templates/pagination.html
{#<style>#}
{#  .pagination-container {#}
{#    display: flex;#}
{#    justify-content: center;#}
{#    margin-top: 20px; /* Отступ сверху */#}
{#    margin-bottom: 20px; /* Отступ снизу */#}
{#  }#}
{##}
{#  .pagination {#}
{#    list-style-type: none;#}
{#    padding: 0;#}
{#  }#}
{##}
{#  .pagination li {#}
{#    display: inline;#}
{#    margin-right: 10px; /* Настроить расстояние между цифрами страниц */#}
{#  }#}
{##}
{#  .pagination .current {#}
{#    font-weight: bold;#}
{#  }#}
{#</style>#}
{##}
{#<div class="pagination-container">#}
{#  <ul class="pagination">#}
{#    {% if page.has_previous %}#}
{#      <li><a href="?{{ clean_query_string }}&page={{ page.previous_page_number }}">Previous</a></li>#}
{#    {% endif %}#}
{##}
{#    <li class="current">#}
{#      Page {{ page.number }} of {{ page.paginator.num_pages }}.#}
{#    </li>#}
{##}
{#    {% if page.has_next %}#}
{#      <li><a href="?{{ clean_query_string }}&page={{ page.next_page_number }}">Next</a></li>#}
{#    {% endif %}#}
{#  </ul>#}
{#</div>#}

{#-----------------#}

<style>
  .pagination-container {
    display: flex;
    justify-content: center;
    margin-top: 20px; /* Отступ сверху */
    margin-bottom: 20px; /* Отступ снизу */
  }

  .pagination {
    list-style-type: none;
    padding: 0;
  }

  .pagination li {
    display: inline;
    margin-right: 10px; /* Настроить расстояние между цифрами страниц */
  }

  .pagination .current {
    font-weight: bold;
  }
</style>

<div class="pagination-container">
  <ul class="pagination">
    {% if page.has_previous %}
      <li><a href="?{{ clean_query_string }}&page={{ page.previous_page_number }}">Previous</a></li>
    {% endif %}

    {% for num in page.paginator.page_range %}
      {% if num == page.number %}
        <li class="current">{{ num }}</li>
      {% elif num > page.number|add:-7 and num < page.number|add:7 %}
        <li><a href="?{{ clean_query_string }}&page={{ num }}">{{ num }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page.has_next %}
      <li><a href="?{{ clean_query_string }}&page={{ page.next_page_number }}">Next</a></li>
    {% endif %}
  </ul>
</div>

templates/search_result.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
{# стили для формы поиска#}
<style>
  .form-inline {
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
  }

  .form-inline .form-group {
    flex: 0 0 100%;
    margin-bottom: 10px;
  }

  .form-inline .form-group .btn-group {
    display: flex;
    align-items: center;
  }

  .form-inline .form-group .btn-group .btn {
    margin-left: 5px;
  }

  @media (min-width: 768px) {
    .form-inline .form-group {
      flex: 0 0 auto;
      margin-right: 10px;
    }

    .form-inline .form-group:last-child {
      margin-right: 0;
    }
  }
</style>






      <!-- ======= Features Section ======= -->
      <section id="features" class="features">
        <div class="container">

        {# ФОРМА ПОИСКА начало#}
<form class="form-inline mt-2 mt-md-0" action="" method="get">
  <div class="form-group">

    <select name="category" class="form-control" onchange="this.form.submit()">
      <option value="">Тип недвижимости</option>
      {% for i in category %}
        <option value="{{ i.pk }}" {% if request.GET.category|stringformat:"s" == i.pk|stringformat:"s" %}selected{% endif %}>{{ i }}</option>
      {% endfor %}
    </select>

  </div>
  <div class="form-group">
    <input name="zapros" class="form-control" type="text" placeholder="Search" aria-label="Search" value="{{ request.GET.zapros }}">
  </div>
  <div class="form-group">
    <input name="min" class="form-control" type="text" placeholder="Min" aria-label="Search" value="{{ request.GET.min }}" pattern="[0-9]*" title="Please enter numbers only">
  </div>
  <div class="form-group">
    <input name="max" class="form-control" type="text" placeholder="Max" aria-label="Search" value="{{ request.GET.max }}" pattern="[0-9]*" title="Please enter numbers only">
  </div>
  <div class="form-group">
    <div class="btn-group">
      <button class="btn btn-outline-success" type="submit">Search</button>
      <button class="btn btn-outline-secondary" type="button" onclick="resetForm(this.form)">Clear</button>
    </div>
  </div>
</form>
        {# ФОРМА ПОИСКА конец#}

        <script>
          function resetForm(form) {
            form.category.value = '';
            form.zapros.value = '';
            form.min.value = '';
            form.max.value = '';
            form.submit();
          }
        </script>



        <br>
        <br>
<style>
  .card {
    margin-bottom: 20px; /* Добавить зазор между карточками */
  }
</style>

<div class="row">
  {% for object in Realty %}
    <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
      <div class="card" data-aos="fade-up">
        <a href="{{ object.get_absolute_url }}"><img src="{{ object.img.url }}" class="card-img-top" alt="..."></a>
        <div class="card-body">
          <i class="bx bx-tachometer"></i>
          <h5 class="card-title"><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h5>
          <p class="card-text">{{ object.info }}</p>
        </div>
      </div>
    </div>
  {% endfor %}
</div>



      {% include 'pagination.html' with page=Realty %}


  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="a{% static 'vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

{% endblock %}

templates/test_mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  Test mail
</body>
</html>

templates/zayavka.html
{% extends 'base.html' %}
  {% load static %}


{% block content %}
<!-- ======= Contact Us Section ======= -->
      <section id="contact" class="contact">
        <div class="container">

          <div class="section-title" data-aos="fade-down">
            <span>Contact Us</span>
            <h2>Contact Us</h2>
          </div>

          <div class="row justify-content-center">
            <div class="col-lg-4 col-md-12" data-aos="fade-up" data-aos-delay="100">
              <div class="info-box">
                <i class="bx bx-map"></i>
                <h3>Our Address</h3>
                <p>A108 Adam Street, New York, NY 535022</p>
              </div>
            </div>
            <div class="col-lg-4 col-md-6 mt-4 mt-lg-0" data-aos="fade-up" data-aos-delay="200">
              <div class="info-box">
                <i class="bx bx-envelope"></i>
                <h3>Email Us</h3>
                <p>info@example.com<br>contact@example.com</p>
              </div>
            </div>
            <div class="col-lg-4 col-md-6 mt-4 mt-lg-0" data-aos="fade-up" data-aos-delay="300">
              <div class="info-box">
                <i class="bx bx-phone-call"></i>
                <h3>Call Us</h3>
                <p>+1 5589 55488 55<br>+1 6678 254445 41</p>
              </div>
            </div>
          </div>

          <form action="" method="post" role="form" class="php-email-form mt-4" data-aos="fade-up" data-aos-delay="400">
                {% csrf_token %}
              <div class="row">

              <div class="col-md-6 form-group">
                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
              </div>



              <div class="col-md-6 form-group mt-3 mt-md-0">
                <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
              </div>
            </div>



            <div class="form-group mt-3">
              <textarea class="form-control" name="question" rows="5" placeholder="Message" required></textarea>
            </div>


            <div class="my-3">
              <div class="loading">Loading</div>
              <div class="error-message"></div>
              <div class="sent-message">Your message has been sent. Thank you!</div>
            </div>
            <div class="text-center"><button type="submit">Send Message</button></div>
          </form>

        </div>
      </section><!-- End Contact Us Section -->
{% endblock %}